version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
      - phpmyadmin

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: db_root_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: db_root_password
    ports:
      - "8181:80"
    depends_on:
      - db

volumes:
  db_data:
